Theme: jekyll-theme-minimal
logo: https://p325k7wa.twic.pics/high/jojo/jojo-bizarre-adventure-all-star-battle-r/02-news/JOJOASBR_launchTrailer_thumbnail.jpg?twic=v1/resize=760/step=10/quality=80
title: Kristiana Wong BIMM143 Class WI24
